### ISSUE TITLE
Maven POM still references GPL 2.0, should be GPL 2.0 With ClassPath Exception

### ISSUE THREAD

**Issue by matth78** [beryx/awt-color-factory#1]
build.gradle needs to change the license section of the POM from "GPL 2.0" to "GPL 2.0 With ClassPath Exception".

Since it is currently GPL 2.0 in the POM, this is the license that gets flagged in Maven Central.  https://mvnrepository.com/artifact/org.beryx/awt-color-factory

**Comment by siordache** [comment]
Thanks for reporting this issue. Fixed in [release 1.0.1](https://search.maven.org/artifact/org.beryx/awt-color-factory/1.0.1/jar).

**Comment by heuermh** [comment]
Thank you for releasing this simple but useful library!  You may want to close this Github issue if as you mention above, it has been fixed in a released version.

**Comment by siordache** [comment]
@heuermh Thanks for your comment. I'm closing it now.
